theme:
    name: material
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/toggle-switch
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to light mode
    features:
        - search.suggest
        - search.highlight
        - search.share
        - navigation.instant
        - navigation.instant.progress
        - toc.follow
        - toc
        - toc.integrate
        - content.code.copy
        - content.code.select
        - content.code.annotate
        - content.tabs.link
        - navigation.tabs
site_name: 192 Support Squadron
nav:
    - Home: index.md
markdown_extensions:
    - toc:
          permalink: true
    - tables:
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite:
    - pymdownx.snippets:
    - pymdownx.superfences:
    - pymdownx.details:
    - admonition:
    - attr_list:
    - md_in_html:
    - pymdownx.tabbed:
          alternate_style: true
plugins:
    - offline
    - search
    - glightbox
    - open-in-new-tab
extra:
    generator: true
